<?php
// src/AppBundle/Config/CoreConfig.php

/**
 * @copyright (c) 2017, Vladimir Zhitkov. All rights reserved.
 */

namespace AppBundle\Config;

/**
 * Application base configuration.
 * 
 * @author Vladimir Zhitkov
 */
class CoreConfig {
    
    const DB = [
        'host' => '127.0.0.1',
        'user' => 'username',
        'pass' => 'userpassword',
        'dbname' => 'thedbname',
    ];
    
    const AUTH_PARAMS = [
        "allowedips" => [
            "127.0.0.1",
        ],
        "username" => "AuthUserName",
        // Password hash generated by PHP's password_hash(). Compares by password_verify().
        "userpassw" => 'GeneratedUserPasswordHash',
    ];
    
}
